package actions

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/nyaruka/goflow/flows"
	"github.com/nyaruka/goflow/flows/events"
)

func init() {
	RegisterType(TypeCallResthook, func() flows.Action { return &CallResthookAction{} })
}

// TypeCallResthook is the type for the call resthook action
const TypeCallResthook string = "call_resthook"

// CallResthookAction can be used to call a resthook.
//
// A [event:webhook_called] event will be created for each subscriber of the resthook with the results
// of the HTTP call. If the action has `result_name` set, a result will
// be created with that name, and if the resthook returns valid JSON, that will be accessible
// through `extra` on the result.
//
//   {
//     "uuid": "8eebd020-1af5-431c-b943-aa670fc74da9",
//     "type": "call_resthook",
//     "resthook": "new-registration"
//   }
//
// @action call_resthook
type CallResthookAction struct {
	BaseAction
	onlineAction

	Resthook   string `json:"resthook" validate:"required"`
	ResultName string `json:"result_name,omitempty"`
}

// NewCallResthookAction creates a new call resthook action
func NewCallResthookAction(uuid flows.ActionUUID, resthook string, resultName string) *CallResthookAction {
	return &CallResthookAction{
		BaseAction: NewBaseAction(TypeCallResthook, uuid),
		Resthook:   resthook,
		ResultName: resultName,
	}
}

// Execute runs this action
func (a *CallResthookAction) Execute(run flows.FlowRun, step flows.Step, logModifier flows.ModifierCallback, logEvent flows.EventCallback) error {
	// NOOP if resthook doesn't exist
	resthook := run.Session().Assets().Resthooks().FindBySlug(a.Resthook)
	if resthook == nil {
		return nil
	}

	// build our payload
	payload, err := run.EvaluateTemplate(flows.DefaultWebhookPayload)
	if err != nil {
		logEvent(events.NewErrorEvent(err))
	}

	// regardless of what subscriber calls we make, we need to record the payload that would be sent
	logEvent(events.NewResthookCalledEvent(a.Resthook, json.RawMessage(payload)))

	// make a call to each subscriber URL
	webhooks := make([]*flows.WebhookCall, 0, len(resthook.Subscribers()))

	for _, url := range resthook.Subscribers() {
		req, err := http.NewRequest("POST", url, strings.NewReader(payload))
		if err != nil {
			logEvent(events.NewErrorEvent(err))
			return nil
		}

		req.Header.Add("Content-Type", "application/json")

		webhook, err := flows.MakeWebhookCall(run.Session(), req, a.Resthook)
		if err != nil {
			logEvent(events.NewErrorEvent(err))
		} else {
			webhooks = append(webhooks, webhook)
			logEvent(events.NewWebhookCalledEvent(webhook))
		}
	}

	asResult := a.pickResultWebhook(webhooks)
	if asResult != nil && a.ResultName != "" {
		a.saveWebhookResult(run, step, a.ResultName, asResult, logEvent)
	}

	return nil
}

// picks one of the resthook calls to become the result generated by this action
func (a *CallResthookAction) pickResultWebhook(calls []*flows.WebhookCall) *flows.WebhookCall {
	var lastSuccess, last410, lastFailure *flows.WebhookCall

	for _, call := range calls {
		switch call.Status() {
		case flows.WebhookStatusSuccess:
			lastSuccess = call
		case flows.WebhookStatusSubscriberGone:
			last410 = call
		default:
			lastFailure = call
		}
	}

	// 1. if we got one or more errors (non-410, non-200), result is last failure
	// 2. if we no errors, no 410s, but at least one success, result is last success
	// 3. if we only got 410s, result is last 410
	if lastFailure != nil {
		return lastFailure
	} else if lastSuccess != nil {
		return lastSuccess
	}
	return last410
}

// Inspect inspects this object and any children
func (a *CallResthookAction) Inspect(inspect func(flows.Inspectable)) {
	inspect(a)
}

// EnumerateResultNames enumerates all result names on this object
func (a *CallResthookAction) EnumerateResultNames(include func(string)) {
	include(a.ResultName)
}
