package triggers_test

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"sort"
	"testing"
	"time"

	"github.com/nyaruka/gocommon/urns"
	"github.com/nyaruka/goflow/assets"
	"github.com/nyaruka/goflow/assets/static"
	"github.com/nyaruka/goflow/envs"
	"github.com/nyaruka/goflow/excellent/types"
	"github.com/nyaruka/goflow/flows"
	"github.com/nyaruka/goflow/flows/engine"
	"github.com/nyaruka/goflow/flows/triggers"
	"github.com/nyaruka/goflow/test"
	"github.com/nyaruka/goflow/utils/dates"
	"github.com/nyaruka/goflow/utils/jsonx"
	"github.com/nyaruka/goflow/utils/uuids"

	"github.com/pkg/errors"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestTriggerTypes(t *testing.T) {
	assetsJSON, err := ioutil.ReadFile("testdata/_assets.json")
	require.NoError(t, err)

	typeNames := make([]string, 0)
	for typeName := range triggers.RegisteredTypes() {
		typeNames = append(typeNames, typeName)
	}

	sort.Strings(typeNames)

	for _, typeName := range typeNames {
		testTriggerType(t, assetsJSON, typeName)
	}
}

func testTriggerType(t *testing.T, assetsJSON json.RawMessage, typeName string) {
	testFile, err := ioutil.ReadFile(fmt.Sprintf("testdata/%s.json", typeName))
	require.NoError(t, err)

	tests := []struct {
		Description string            `json:"description"`
		Trigger     json.RawMessage   `json:"trigger"`
		ReadError   string            `json:"read_error"`
		Events      []json.RawMessage `json:"events"`
		Context     json.RawMessage   `json:"context"`
	}{}

	err = jsonx.Unmarshal(testFile, &tests)
	require.NoError(t, err)

	defer dates.SetNowSource(dates.DefaultNowSource)
	defer uuids.SetGenerator(uuids.DefaultGenerator)

	for _, tc := range tests {
		dates.SetNowSource(dates.NewFixedNowSource(time.Date(2018, 10, 18, 14, 20, 30, 123456, time.UTC)))
		uuids.SetGenerator(uuids.NewSeededGenerator(12345))

		testName := fmt.Sprintf("test '%s' for trigger type '%s'", tc.Description, typeName)

		// create session assets
		sa, err := test.CreateSessionAssets(assetsJSON, "")
		require.NoError(t, err, "unable to create session assets in %s", testName)

		trigger, err := triggers.ReadTrigger(sa, tc.Trigger, assets.PanicOnMissing)

		if tc.ReadError != "" {
			rootErr := errors.Cause(err)
			assert.EqualError(t, rootErr, tc.ReadError, "read error mismatch in %s", testName)
			continue
		} else {
			assert.NoError(t, err, "unexpected read error in %s", testName)
		}

		// start a session with this trigger
		eng := engine.NewBuilder().Build()
		session, sprint, err := eng.NewSession(sa, trigger)
		assert.NoError(t, err)

		assert.Equal(t, flows.FlowTypeMessaging, session.Type())
		assert.NotNil(t, session.Environment())

		// check events generated by trigger
		actualEventsJSON, _ := jsonx.Marshal(sprint.Events())
		expectedEventsJSON, _ := jsonx.Marshal(tc.Events)
		test.AssertEqualJSON(t, expectedEventsJSON, actualEventsJSON, "events mismatch in %s", testName)

		// check context representation
		actualContextJSON, err := session.Runs()[0].EvaluateTemplate(`@(json(trigger))`)
		assert.NoError(t, err)
		test.AssertEqualJSON(t, tc.Context, []byte(actualContextJSON), "context mismatch in %s", testName)

		// try marshaling the trigger back to JSON
		triggerJSON, err := jsonx.Marshal(trigger)
		test.AssertEqualJSON(t, tc.Trigger, triggerJSON, "marshal mismatch in %s", testName)
	}
}

var assetsJSON = `{
	"flows": [
		{
			"uuid": "7c37d7e5-6468-4b31-8109-ced2ef8b5ddc",
			"name": "Registration",
            "spec_version": "13.0",
            "language": "eng",
            "type": "messaging",
            "nodes": []
        }
	],
	"channels": [
		{
			"uuid": "8cd472c4-bb85-459a-8c9a-c04708af799e",
			"name": "Facebook",
			"address": "23532562626",
			"schemes": ["facebook"],
			"roles": ["send", "receive"]
		},
		{
            "uuid": "3a05eaf5-cb1b-4246-bef1-f277419c83a7",
            "name": "Nexmo",
            "address": "+16055742523",
            "schemes": ["tel"],
            "roles": ["send", "receive"]
        }
	]
}`

func TestTriggerMarshaling(t *testing.T) {
	defer dates.SetNowSource(dates.DefaultNowSource)
	dates.SetNowSource(dates.NewFixedNowSource(time.Date(2018, 10, 20, 9, 49, 30, 1234567890, time.UTC)))

	uuids.SetGenerator(uuids.NewSeededGenerator(1234))
	defer uuids.SetGenerator(uuids.DefaultGenerator)

	env := envs.NewBuilder().Build()

	source, err := static.NewSource([]byte(assetsJSON))
	require.NoError(t, err)

	sa, err := engine.NewSessionAssets(env, source, nil)
	require.NoError(t, err)

	flow := assets.NewFlowReference(assets.FlowUUID("7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"), "Registration")
	channel := assets.NewChannelReference("3a05eaf5-cb1b-4246-bef1-f277419c83a7", "Nexmo")

	contact := flows.NewEmptyContact(sa, "Bob", envs.Language("eng"), nil)
	contact.AddURN(urns.URN("tel:+12065551212"), nil)

	// can't create a trigger with invalid JSON
	_, err = triggers.NewFlowAction(
		env,
		flow,
		contact,
		json.RawMessage(`{"uuid"}`),
		false,
	)
	assert.EqualError(t, err, `invalid run summary JSON: {"uuid"}`)

	_, err = triggers.NewFlowAction(
		env,
		flow,
		contact,
		nil,
		false,
	)
	assert.EqualError(t, err, `invalid run summary JSON: `)

	flowAction, _ := triggers.NewFlowAction(
		env,
		flow,
		contact,
		json.RawMessage(`{"uuid": "084e4bed-667c-425e-82f7-bdb625e6ec9e"}`),
		false,
	)

	triggerTests := []struct {
		trigger   flows.Trigger
		marshaled string
	}{
		{
			triggers.NewCampaign(
				env,
				flow,
				contact,
				triggers.NewCampaignEvent("8d339613-f0be-48b7-92ee-155f4c7576f8", triggers.NewCampaignReference("8cd472c4-bb85-459a-8c9a-c04708af799e", "Reminders")),
			),
			`{
				"contact": {
					"created_on": "2018-10-20T09:49:31.23456789Z",
					"language": "eng",
					"name": "Bob",
					"status": "active",
					"urns": ["tel:+12065551212"],
					"uuid": "c00e5d67-c275-4389-aded-7d8b151cbd5b"
				},
				"environment": {
					"date_format": "YYYY-MM-DD",
					"max_value_length": 640,
					"number_format": {
						"decimal_symbol": ".",
						"digit_grouping_symbol": ","
					},
					"redaction_policy": "none",
					"time_format": "tt:mm",
					"timezone": "UTC"
				},
				"event": {
					"campaign": {
						"name": "Reminders",
						"uuid": "8cd472c4-bb85-459a-8c9a-c04708af799e"
					},
					"uuid": "8d339613-f0be-48b7-92ee-155f4c7576f8"
				},
				"flow": {
					"name": "Registration",
					"uuid": "7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"
				},
				"triggered_on": "2018-10-20T09:49:31.23456789Z",
				"type": "campaign"
			}`,
		},
		{
			triggers.NewChannel(
				env,
				flow,
				contact,
				triggers.NewChannelEvent(triggers.ChannelEventTypeNewConversation, channel),
				nil,
			),
			`{
				"contact": {
					"created_on": "2018-10-20T09:49:31.23456789Z",
					"language": "eng",
					"name": "Bob",
					"status": "active",
					"urns": ["tel:+12065551212"],
					"uuid": "c00e5d67-c275-4389-aded-7d8b151cbd5b"
				},
				"environment": {
					"date_format": "YYYY-MM-DD",
					"max_value_length": 640,
					"number_format": {
						"decimal_symbol": ".",
						"digit_grouping_symbol": ","
					},
					"redaction_policy": "none",
					"time_format": "tt:mm",
					"timezone": "UTC"
				},
				"event": {
					"channel": {
						"name": "Nexmo",
						"uuid": "3a05eaf5-cb1b-4246-bef1-f277419c83a7"
					},
					"type": "new_conversation"
				},
				"flow": {
					"name": "Registration",
					"uuid": "7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"
				},
				"params": {},
				"triggered_on": "2018-10-20T09:49:31.23456789Z",
				"type": "channel"
			}`,
		},
		{
			flowAction,
			`{
				"contact": {
					"created_on": "2018-10-20T09:49:31.23456789Z",
					"language": "eng",
					"name": "Bob",
					"status": "active",
					"urns": ["tel:+12065551212"],
					"uuid": "c00e5d67-c275-4389-aded-7d8b151cbd5b"
				},
				"environment": {
					"date_format": "YYYY-MM-DD",
					"max_value_length": 640,
					"number_format": {
						"decimal_symbol": ".",
						"digit_grouping_symbol": ","
					},
					"redaction_policy": "none",
					"time_format": "tt:mm",
					"timezone": "UTC"
				},
				"flow": {
					"name": "Registration",
					"uuid": "7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"
				},
				"run_summary": {
					"uuid": "084e4bed-667c-425e-82f7-bdb625e6ec9e"
				},
				"triggered_on": "2018-10-20T09:49:31.23456789Z",
				"type": "flow_action"
			}`,
		},
		{
			triggers.NewIncomingCall(
				env,
				flow,
				contact,
				urns.URN("tel:+12065551212"),
				channel,
			),
			`{
				"connection": {
					"channel": {
						"name": "Nexmo",
						"uuid": "3a05eaf5-cb1b-4246-bef1-f277419c83a7"
					},
					"urn": "tel:+12065551212"
				},
				"contact": {
					"created_on": "2018-10-20T09:49:31.23456789Z",
					"language": "eng",
					"name": "Bob",
					"status": "active",
					"urns": ["tel:+12065551212"],
					"uuid": "c00e5d67-c275-4389-aded-7d8b151cbd5b"
				},
				"environment": {
					"date_format": "YYYY-MM-DD",
					"max_value_length": 640,
					"number_format": {
						"decimal_symbol": ".",
						"digit_grouping_symbol": ","
					},
					"redaction_policy": "none",
					"time_format": "tt:mm",
					"timezone": "UTC"
				},
				"event": {
					"channel": {
						"name": "Nexmo",
						"uuid": "3a05eaf5-cb1b-4246-bef1-f277419c83a7"
					},
					"type": "incoming_call"
				},
				"flow": {
					"name": "Registration",
					"uuid": "7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"
				},
				"params": {},
				"triggered_on": "2018-10-20T09:49:31.23456789Z",
				"type": "channel"
			}`,
		},
		{
			triggers.NewManual(
				env,
				flow,
				contact,
				true,
				types.NewXObject(map[string]types.XValue{"foo": types.NewXText("bar")}),
			),
			`{
				"contact": {
					"created_on": "2018-10-20T09:49:31.23456789Z",
					"language": "eng",
					"name": "Bob",
					"status": "active",
					"urns": ["tel:+12065551212"],
					"uuid": "c00e5d67-c275-4389-aded-7d8b151cbd5b"
				},
				"environment": {
					"date_format": "YYYY-MM-DD",
					"max_value_length": 640,
					"number_format": {
						"decimal_symbol": ".",
						"digit_grouping_symbol": ","
					},
					"redaction_policy": "none",
					"time_format": "tt:mm",
					"timezone": "UTC"
				},
				"flow": {
					"name": "Registration",
					"uuid": "7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"
				},
				"batch": true,
				"params": {
					"foo": "bar"
				},
				"triggered_on": "2018-10-20T09:49:31.23456789Z",
				"type": "manual"
			}`,
		},
		{
			triggers.NewManualVoice(
				env,
				flow,
				contact,
				flows.NewConnection(channel, "tel:+12065551212"),
				true,
				types.NewXObject(map[string]types.XValue{"foo": types.NewXText("bar")}),
			),
			`{
				"connection": {
					"channel": {
						"name": "Nexmo",
						"uuid": "3a05eaf5-cb1b-4246-bef1-f277419c83a7"
					},
					"urn": "tel:+12065551212"
				},
				"contact": {
					"created_on": "2018-10-20T09:49:31.23456789Z",
					"language": "eng",
					"name": "Bob",
					"status": "active",
					"urns": ["tel:+12065551212"],
					"uuid": "c00e5d67-c275-4389-aded-7d8b151cbd5b"
				},
				"environment": {
					"date_format": "YYYY-MM-DD",
					"max_value_length": 640,
					"number_format": {
						"decimal_symbol": ".",
						"digit_grouping_symbol": ","
					},
					"redaction_policy": "none",
					"time_format": "tt:mm",
					"timezone": "UTC"
				},
				"flow": {
					"name": "Registration",
					"uuid": "7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"
				},
				"batch": true,
				"params": {
					"foo": "bar"
				},
				"triggered_on": "2018-10-20T09:49:31.23456789Z",
				"type": "manual"
			}`,
		},
		{
			triggers.NewMsg(
				env,
				flow,
				contact,
				flows.NewMsgIn(flows.MsgUUID("c8005ee3-4628-4d76-be66-906352cb1935"), urns.URN("tel:+1234567890"), channel, "Hi there", nil),
				triggers.NewKeywordMatch(triggers.KeywordMatchTypeFirstWord, "hi"),
			),
			`{
				"contact": {
					"created_on": "2018-10-20T09:49:31.23456789Z",
					"language": "eng",
					"name": "Bob",
					"status": "active",
					"urns": ["tel:+12065551212"],
					"uuid": "c00e5d67-c275-4389-aded-7d8b151cbd5b"
				},
				"environment": {
					"date_format": "YYYY-MM-DD",
					"max_value_length": 640,
					"number_format": {
						"decimal_symbol": ".",
						"digit_grouping_symbol": ","
					},
					"redaction_policy": "none",
					"time_format": "tt:mm",
					"timezone": "UTC"
				},
				"flow": {
					"name": "Registration",
					"uuid": "7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"
				},
				"keyword_match": {
					"keyword": "hi",
					"type": "first_word"
				},
				"msg": {
					"channel": {
						"name": "Nexmo",
						"uuid": "3a05eaf5-cb1b-4246-bef1-f277419c83a7"
					},
					"text": "Hi there",
					"urn": "tel:+1234567890",
					"uuid": "c8005ee3-4628-4d76-be66-906352cb1935"
				},
				"triggered_on": "2018-10-20T09:49:31.23456789Z",
				"type": "msg"
			}`,
		},
	}

	for _, tc := range triggerTests {
		triggerJSON, err := jsonx.Marshal(tc.trigger)
		assert.NoError(t, err)

		test.AssertEqualJSON(t, []byte(tc.marshaled), triggerJSON, "trigger JSON mismatch")

		// then try to read from the JSON
		_, err = triggers.ReadTrigger(sa, triggerJSON, assets.PanicOnMissing)
		assert.NoError(t, err, "error reading trigger: %s", string(triggerJSON))
	}
}

func TestReadTrigger(t *testing.T) {
	env := envs.NewBuilder().Build()

	missingAssets := make([]assets.Reference, 0)
	missing := func(a assets.Reference, err error) { missingAssets = append(missingAssets, a) }

	sessionAssets, err := engine.NewSessionAssets(env, static.NewEmptySource(), nil)
	require.NoError(t, err)

	// error if no type field
	_, err = triggers.ReadTrigger(sessionAssets, []byte(`{"foo": "bar"}`), missing)
	assert.EqualError(t, err, "field 'type' is required")

	// error if we don't recognize action type
	_, err = triggers.ReadTrigger(sessionAssets, []byte(`{"type": "do_the_foo", "foo": "bar"}`), missing)
	assert.EqualError(t, err, "unknown type: 'do_the_foo'")
}

func TestTriggerSessionInitialization(t *testing.T) {
	env := envs.NewBuilder().WithDateFormat(envs.DateFormatMonthDayYear).Build()

	source, err := static.NewSource([]byte(assetsJSON))
	require.NoError(t, err)

	sa, err := engine.NewSessionAssets(env, source, nil)
	require.NoError(t, err)

	defaultEnv := envs.NewBuilder().Build()

	flow := assets.NewFlowReference(assets.FlowUUID("7c37d7e5-6468-4b31-8109-ced2ef8b5ddc"), "Registration")

	contact := flows.NewEmptyContact(sa, "Bob", envs.Language("eng"), nil)
	contact.AddURN(urns.URN("tel:+12065551212"), nil)

	params := types.NewXObject(map[string]types.XValue{"foo": types.NewXText("bar")})

	trigger := triggers.NewManual(
		env,
		flow,
		contact,
		false,
		params,
	)

	assert.Equal(t, triggers.TypeManual, trigger.Type())
	assert.Equal(t, env, trigger.Environment())
	assert.Equal(t, contact, trigger.Contact())
	assert.Nil(t, trigger.Connection())
	assert.Equal(t, params, trigger.Params())

	eng := engine.NewBuilder().Build()
	session, _, err := eng.NewSession(sa, trigger)
	require.NoError(t, err)

	assert.Equal(t, flows.FlowTypeMessaging, session.Type())
	assert.Equal(t, contact, session.Contact())
	assert.Equal(t, env, session.Environment())
	assert.Equal(t, flow, session.Runs()[0].FlowReference())

	// contact, environment and params are optional
	trigger = triggers.NewManual(
		nil,
		flow,
		nil,
		false,
		nil,
	)

	assert.Equal(t, triggers.TypeManual, trigger.Type())
	assert.Nil(t, trigger.Environment())
	assert.Nil(t, trigger.Contact())
	assert.Nil(t, trigger.Params())

	session, _, err = eng.NewSession(sa, trigger)
	require.NoError(t, err)

	assert.Equal(t, flows.FlowTypeMessaging, session.Type())
	assert.Nil(t, session.Contact())
	assert.Equal(t, defaultEnv, session.Environment()) // uses defaults
}
